language: cpp
compiler: g++-4.8
sudo: false
addons:
  apt: 
   sources: ['ubuntu-toolchain-r-test']
   packages: ['gcc-4.8', 'g++-4.8', 'gcov-4.8', 'clang', 'doxygen', 'libgtest-dev', 'libboost-dev']

env:
  - DIR=Lab5 COMPILER=g++-4.8

install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - cd -
    - ls /usr/bin/g++*

before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++
    - gcov --version | grep gcov
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version

script:
    - cd $DIR
    - ls -al
    - g++ --version | grep g++
    - nproc
    - lscpu
    - make test.cpp CXX=$COMPILER -j3