sudo: false
language: cpp
compiler: g++-4.8

addons:
  apt: 
   sources: ['ubuntu-toolchain-r-test']
   # packages: ['gcc-4.8', 'g++-4.8', 'libboost-dev', 'libgtest-dev']
   packages: ['g++-4.8','libgtest-dev']

env: ['DIR=Assignment4','DIR=Assignment4-Zhi','DIR=Lab5']

install: 
  # Set the default compiler that 'make' uses to g++-4.8
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - export CXX="g++-4.8"
  # Install gtest without sudo 
  # Create directory to install into
  - mkdir ~/gtest && cd ~/gtest
  # Create environment variable for 'make'
  - export LIBRARY_PATH=$(pwd)
  # cmake gtest into the current directory
  - cmake /usr/src/gtest/
  # make gtest
  - make -j14
  # chage directory back to previous directory
  - cd -

before_script:
  # Verify the version information of the installed binaries
  - uname -a
  - printenv
  # http://stackoverflow.com/questions/818255/in-the-shell-what-does-21-mean
  # - $CC --version 2>&1 | grep gcc
  - $CXX --version 2>&1 | grep g++
  # - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp

script:
  - cd $DIR
  - make -B -j14 && make test


# $ lscpu
# Architecture:          x86_64
# CPU op-mode(s):        32-bit, 64-bit
# Byte Order:            Little Endian
# CPU(s):                32
# On-line CPU(s) list:   0-31
# Thread(s) per core:    2
# Core(s) per socket:    8
# Socket(s):             2
# NUMA node(s):          2
# Vendor ID:             GenuineIntel
# CPU family:            6
# Model:                 62
# Stepping:              4
# CPU MHz:               2793.328
# BogoMIPS:              5660.02
# Hypervisor vendor:     Xen
# Virtualization type:   full
# L1d cache:             32K
# L1i cache:             32K
# L2 cache:              256K
# L3 cache:              25600K
# NUMA node0 CPU(s):     0-7,16-23
# NUMA node1 CPU(s):     8-15,24-31

# nproc
# 2